[package]
name = "thrive-server"
version = "0.1.0"
authors = ["Tobias Walle <git.tobias@walle.email>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-files = "0.5"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
anyhow = "1"
portpicker = "0.1"